package main

import (
	"strings"

	"google.golang.org/protobuf/compiler/protogen"
	"google.golang.org/protobuf/proto"
	"google.golang.org/protobuf/reflect/protoreflect"
	"google.golang.org/protobuf/types/pluginpb"

	settersv1 "ztg/gen/go/setters/v1"
)

func main() {
	protogen.Options{}.Run(func(plugin *protogen.Plugin) error {
		plugin.SupportedFeatures = uint64(
			pluginpb.CodeGeneratorResponse_FEATURE_PROTO3_OPTIONAL,
		)

		for _, file := range plugin.Files {
			if !file.Generate {
				continue
			}
			generateFile(plugin, file)
		}
		return nil
	})
}

func generateFile(plugin *protogen.Plugin, file *protogen.File) {
	for _, msg := range file.Messages {
		if !hasGenerateSetters(msg) {
			continue
		}

		filename := file.GeneratedFilenamePrefix + "_" + msg.GoIdent.GoName + "_setters.pb.go"
		g := plugin.NewGeneratedFile(filename, file.GoImportPath)

		g.P("// Code generated by protoc-gen-setters. DO NOT EDIT.")
		g.P()
		g.P("package ", file.GoPackageName)
		g.P()

		generateMessageSetters(g, msg)
	}
}

func hasGenerateSetters(msg *protogen.Message) bool {
	opts := msg.Desc.Options()
	if opts == nil {
		return false
	}

	val := proto.GetExtension(opts, settersv1.E_GenerateSetters)
	b, ok := val.(bool)
	return ok && b
}

func generateMessageSetters(g *protogen.GeneratedFile, msg *protogen.Message) {
	for _, field := range msg.Fields {
		// Skip real oneofs, but allow proto3 optional fields (which appear as synthetic oneofs)
		if field.Oneof != nil && !field.Desc.HasOptionalKeyword() {
			continue
		}

		goField := field.GoName

		// Determine the correct parameter type based on field kind
		var paramType string
		switch field.Desc.Kind() {
		case protoreflect.MessageKind, protoreflect.GroupKind:
			// For message types, use the message's Go name
			if field.Message != nil {
				paramType = string(g.QualifiedGoIdent(field.Message.GoIdent))
			} else {
				paramType = string(g.QualifiedGoIdent(field.GoIdent))
			}
		default:
			// For scalar types, use the GoIdent
			paramType = string(g.QualifiedGoIdent(field.GoIdent))
		}

		// Receiver name: first letter lowercased
		recv := strings.ToLower(msg.GoIdent.GoName[:1])

		g.P("func (", recv, " *", msg.GoIdent.GoName, ") Set", goField, "(v *", paramType, ") {")
		g.P("    ", recv, ".", goField, " = v")
		g.P("}")
		g.P()
	}
}
