// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"context"
	"database/sql"
)

type Querier interface {
	CountIdentities(ctx context.Context, isTrusted sql.NullBool) (int64, error)
	DeleteIdentity(ctx context.Context, publicKey []byte) error
	GetIdentityByAddress(ctx context.Context, serverAddress string) (Identity, error)
	GetIdentityByKey(ctx context.Context, publicKey []byte) (Identity, error)
	InsertIdentity(ctx context.Context, arg InsertIdentityParams) (Identity, error)
	ListIdentities(ctx context.Context, arg ListIdentitiesParams) ([]Identity, error)
	SetTrustStatus(ctx context.Context, arg SetTrustStatusParams) error
	UpdateLastSeen(ctx context.Context, arg UpdateLastSeenParams) error
}

var _ Querier = (*Queries)(nil)
