// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: factorfight.proto

package factorfight

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	FactorFightService_ReceiveMove_FullMethodName = "/factorfight.FactorFightService/ReceiveMove"
)

// FactorFightServiceClient is the client API for FactorFightService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Service defining RPCs for FactorFight game interactions.
type FactorFightServiceClient interface {
	// SubmitMove allows a player to submit their move.
	ReceiveMove(ctx context.Context, in *Move, opts ...grpc.CallOption) (*Empty, error)
}

type factorFightServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewFactorFightServiceClient(cc grpc.ClientConnInterface) FactorFightServiceClient {
	return &factorFightServiceClient{cc}
}

func (c *factorFightServiceClient) ReceiveMove(ctx context.Context, in *Move, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, FactorFightService_ReceiveMove_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FactorFightServiceServer is the server API for FactorFightService service.
// All implementations must embed UnimplementedFactorFightServiceServer
// for forward compatibility.
//
// Service defining RPCs for FactorFight game interactions.
type FactorFightServiceServer interface {
	// SubmitMove allows a player to submit their move.
	ReceiveMove(context.Context, *Move) (*Empty, error)
	mustEmbedUnimplementedFactorFightServiceServer()
}

// UnimplementedFactorFightServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedFactorFightServiceServer struct{}

func (UnimplementedFactorFightServiceServer) ReceiveMove(context.Context, *Move) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReceiveMove not implemented")
}
func (UnimplementedFactorFightServiceServer) mustEmbedUnimplementedFactorFightServiceServer() {}
func (UnimplementedFactorFightServiceServer) testEmbeddedByValue()                            {}

// UnsafeFactorFightServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FactorFightServiceServer will
// result in compilation errors.
type UnsafeFactorFightServiceServer interface {
	mustEmbedUnimplementedFactorFightServiceServer()
}

func RegisterFactorFightServiceServer(s grpc.ServiceRegistrar, srv FactorFightServiceServer) {
	// If the following call pancis, it indicates UnimplementedFactorFightServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&FactorFightService_ServiceDesc, srv)
}

func _FactorFightService_ReceiveMove_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Move)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FactorFightServiceServer).ReceiveMove(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FactorFightService_ReceiveMove_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FactorFightServiceServer).ReceiveMove(ctx, req.(*Move))
	}
	return interceptor(ctx, in, info, handler)
}

// FactorFightService_ServiceDesc is the grpc.ServiceDesc for FactorFightService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FactorFightService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "factorfight.FactorFightService",
	HandlerType: (*FactorFightServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ReceiveMove",
			Handler:    _FactorFightService_ReceiveMove_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "factorfight.proto",
}
