// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        v5.29.3
// source: proto/factorfight.proto

package factorfight

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Represents a single PawnMove in the FactorFight game.
type PawnMove struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        int32                  `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"` // Result of the move
	Bump          int32                  `protobuf:"varint,2,opt,name=bump,proto3" json:"bump,omitempty"`     // Bump status (encoded as integer)
	Expr          string                 `protobuf:"bytes,3,opt,name=expr,proto3" json:"expr,omitempty"`      // Expression for the move (serialized as a string)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PawnMove) Reset() {
	*x = PawnMove{}
	mi := &file_proto_factorfight_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PawnMove) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PawnMove) ProtoMessage() {}

func (x *PawnMove) ProtoReflect() protoreflect.Message {
	mi := &file_proto_factorfight_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PawnMove.ProtoReflect.Descriptor instead.
func (*PawnMove) Descriptor() ([]byte, []int) {
	return file_proto_factorfight_proto_rawDescGZIP(), []int{0}
}

func (x *PawnMove) GetResult() int32 {
	if x != nil {
		return x.Result
	}
	return 0
}

func (x *PawnMove) GetBump() int32 {
	if x != nil {
		return x.Bump
	}
	return 0
}

func (x *PawnMove) GetExpr() string {
	if x != nil {
		return x.Expr
	}
	return ""
}

// Represents a player's move in the FactorFight game.
type Move struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pawn1         *PawnMove              `protobuf:"bytes,1,opt,name=pawn1,proto3" json:"pawn1,omitempty"` // Pawn1's move
	Pawn2         *PawnMove              `protobuf:"bytes,2,opt,name=pawn2,proto3" json:"pawn2,omitempty"` // Pawn2's move
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Move) Reset() {
	*x = Move{}
	mi := &file_proto_factorfight_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Move) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Move) ProtoMessage() {}

func (x *Move) ProtoReflect() protoreflect.Message {
	mi := &file_proto_factorfight_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Move.ProtoReflect.Descriptor instead.
func (*Move) Descriptor() ([]byte, []int) {
	return file_proto_factorfight_proto_rawDescGZIP(), []int{1}
}

func (x *Move) GetPawn1() *PawnMove {
	if x != nil {
		return x.Pawn1
	}
	return nil
}

func (x *Move) GetPawn2() *PawnMove {
	if x != nil {
		return x.Pawn2
	}
	return nil
}

// Empty message for responses without content.
type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_proto_factorfight_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_proto_factorfight_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_proto_factorfight_proto_rawDescGZIP(), []int{2}
}

var File_proto_factorfight_proto protoreflect.FileDescriptor

var file_proto_factorfight_proto_rawDesc = string([]byte{
	0x0a, 0x17, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x66, 0x61, 0x63, 0x74, 0x6f, 0x72, 0x66, 0x69,
	0x67, 0x68, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0b, 0x66, 0x61, 0x63, 0x74, 0x6f,
	0x72, 0x66, 0x69, 0x67, 0x68, 0x74, 0x22, 0x4a, 0x0a, 0x08, 0x50, 0x61, 0x77, 0x6e, 0x4d, 0x6f,
	0x76, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x62, 0x75,
	0x6d, 0x70, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x62, 0x75, 0x6d, 0x70, 0x12, 0x12,
	0x0a, 0x04, 0x65, 0x78, 0x70, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x65, 0x78,
	0x70, 0x72, 0x22, 0x60, 0x0a, 0x04, 0x4d, 0x6f, 0x76, 0x65, 0x12, 0x2b, 0x0a, 0x05, 0x70, 0x61,
	0x77, 0x6e, 0x31, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x66, 0x61, 0x63, 0x74,
	0x6f, 0x72, 0x66, 0x69, 0x67, 0x68, 0x74, 0x2e, 0x50, 0x61, 0x77, 0x6e, 0x4d, 0x6f, 0x76, 0x65,
	0x52, 0x05, 0x70, 0x61, 0x77, 0x6e, 0x31, 0x12, 0x2b, 0x0a, 0x05, 0x70, 0x61, 0x77, 0x6e, 0x32,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x66, 0x61, 0x63, 0x74, 0x6f, 0x72, 0x66,
	0x69, 0x67, 0x68, 0x74, 0x2e, 0x50, 0x61, 0x77, 0x6e, 0x4d, 0x6f, 0x76, 0x65, 0x52, 0x05, 0x70,
	0x61, 0x77, 0x6e, 0x32, 0x22, 0x07, 0x0a, 0x05, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x32, 0x4a, 0x0a,
	0x12, 0x46, 0x61, 0x63, 0x74, 0x6f, 0x72, 0x46, 0x69, 0x67, 0x68, 0x74, 0x53, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x12, 0x34, 0x0a, 0x0b, 0x52, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x4d, 0x6f,
	0x76, 0x65, 0x12, 0x11, 0x2e, 0x66, 0x61, 0x63, 0x74, 0x6f, 0x72, 0x66, 0x69, 0x67, 0x68, 0x74,
	0x2e, 0x4d, 0x6f, 0x76, 0x65, 0x1a, 0x12, 0x2e, 0x66, 0x61, 0x63, 0x74, 0x6f, 0x72, 0x66, 0x69,
	0x67, 0x68, 0x74, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x42, 0x13, 0x5a, 0x11, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2f, 0x66, 0x61, 0x63, 0x74, 0x6f, 0x72, 0x66, 0x69, 0x67, 0x68, 0x74, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
})

var (
	file_proto_factorfight_proto_rawDescOnce sync.Once
	file_proto_factorfight_proto_rawDescData []byte
)

func file_proto_factorfight_proto_rawDescGZIP() []byte {
	file_proto_factorfight_proto_rawDescOnce.Do(func() {
		file_proto_factorfight_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_factorfight_proto_rawDesc), len(file_proto_factorfight_proto_rawDesc)))
	})
	return file_proto_factorfight_proto_rawDescData
}

var file_proto_factorfight_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proto_factorfight_proto_goTypes = []any{
	(*PawnMove)(nil), // 0: factorfight.PawnMove
	(*Move)(nil),     // 1: factorfight.Move
	(*Empty)(nil),    // 2: factorfight.Empty
}
var file_proto_factorfight_proto_depIdxs = []int32{
	0, // 0: factorfight.Move.pawn1:type_name -> factorfight.PawnMove
	0, // 1: factorfight.Move.pawn2:type_name -> factorfight.PawnMove
	1, // 2: factorfight.FactorFightService.ReceiveMove:input_type -> factorfight.Move
	2, // 3: factorfight.FactorFightService.ReceiveMove:output_type -> factorfight.Empty
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_factorfight_proto_init() }
func file_proto_factorfight_proto_init() {
	if File_proto_factorfight_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_factorfight_proto_rawDesc), len(file_proto_factorfight_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_factorfight_proto_goTypes,
		DependencyIndexes: file_proto_factorfight_proto_depIdxs,
		MessageInfos:      file_proto_factorfight_proto_msgTypes,
	}.Build()
	File_proto_factorfight_proto = out.File
	file_proto_factorfight_proto_goTypes = nil
	file_proto_factorfight_proto_depIdxs = nil
}
