syntax = "proto3";

package game.v1;

// ChallengeRequest is used to tell your server to challenge another server
import "identity/v1/identity.proto";

option go_package = "github.com/calvinmclean/ztg/gen/go/proto/game/v1";

// A generic empty response message.
message Empty {}

message ChallengeRequest {
  string target = 1;
  string game_id = 2;
}

message SignedChallengeRequest {
  ChallengeRequest challenge = 1;
  identity.v1.Signature signature = 2; // Owner must sign the Challenge message using OrderedSignature (see FactorFight precedent)
}

message ChallengeResponse {
  optional bool win = 1; // optional to avoid omitempty when false
  string message = 2;
}

// GameService defines gRPC services for game initiation.
service GameService {
  rpc Challenge(SignedChallengeRequest) returns (ChallengeResponse);
}
