version: "3"

tasks:
  dev1:
    env:
      ZTG_ADDRESS: ":50052"
    cmds:
      - go run main.go

  dev2:
    env:
      ZTG_ADDRESS: ":50053"
    cmds:
      - go run main.go

  factorfight:
    cmds:
      - grpcurl -plaintext -d '{"target":"localhost:50053", "game_id":"ztg.FactorFight.v1"}' localhost:50052 game.v1.GameService/Challenge

  highroll:
    cmds:
      - grpcurl -plaintext -d '{"target":"localhost:50053", "game_id":"ztg.HighRoll.v1"}' localhost:50052 game.v1.GameService/Challenge

  identity:
    cmds:
      - grpcurl -plaintext -d '{}' localhost:50052 identity.v1.IdentityService/GetIdentity

  generate:
    cmds:
      - buf generate
