syntax = "proto3";

package dice.v1;

import "identity/v1/identity.proto";
import "setters/v1/options.proto";

option go_package = "ztg/gen/go/dice/v1";

// MessageType represents the type of the message being sent.
enum MessageType {
  MESSAGE_TYPE_UNSPECIFIED = 0;
  MESSAGE_TYPE_COMMITMENT = 1;
  MESSAGE_TYPE_SECRET = 2;
  MESSAGE_TYPE_ROLL_CONFIRMATION = 3;
}

// Message represents data exchanged between peers.
message Message {
  MessageType msg_type = 1; // Type of the message (e.g., Commitment, Secret, etc.)
  bytes data = 2; // Binary data content (e.g., commitment hash, secret)
}

message SignedMessage {
  option (setters.v1.generate_setters) = true;

  Message message = 1;
  optional identity.v1.Signature signature = 2;
}

service DiceService {
  rpc Roll(stream SignedMessage) returns (stream SignedMessage);
}
