// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: dice.proto

package dice

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RollerService_ReceiveMessage_FullMethodName = "/dice.RollerService/ReceiveMessage"
)

// RollerServiceClient is the client API for RollerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// RollerService defines the gRPC service for interacting with dice rollers.
type RollerServiceClient interface {
	// ReceiveMessage allows sending messages and receives an empty response.
	ReceiveMessage(ctx context.Context, in *Message, opts ...grpc.CallOption) (*Empty, error)
}

type rollerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRollerServiceClient(cc grpc.ClientConnInterface) RollerServiceClient {
	return &rollerServiceClient{cc}
}

func (c *rollerServiceClient) ReceiveMessage(ctx context.Context, in *Message, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, RollerService_ReceiveMessage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RollerServiceServer is the server API for RollerService service.
// All implementations must embed UnimplementedRollerServiceServer
// for forward compatibility.
//
// RollerService defines the gRPC service for interacting with dice rollers.
type RollerServiceServer interface {
	// ReceiveMessage allows sending messages and receives an empty response.
	ReceiveMessage(context.Context, *Message) (*Empty, error)
	mustEmbedUnimplementedRollerServiceServer()
}

// UnimplementedRollerServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRollerServiceServer struct{}

func (UnimplementedRollerServiceServer) ReceiveMessage(context.Context, *Message) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReceiveMessage not implemented")
}
func (UnimplementedRollerServiceServer) mustEmbedUnimplementedRollerServiceServer() {}
func (UnimplementedRollerServiceServer) testEmbeddedByValue()                       {}

// UnsafeRollerServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RollerServiceServer will
// result in compilation errors.
type UnsafeRollerServiceServer interface {
	mustEmbedUnimplementedRollerServiceServer()
}

func RegisterRollerServiceServer(s grpc.ServiceRegistrar, srv RollerServiceServer) {
	// If the following call pancis, it indicates UnimplementedRollerServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RollerService_ServiceDesc, srv)
}

func _RollerService_ReceiveMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Message)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RollerServiceServer).ReceiveMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RollerService_ReceiveMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RollerServiceServer).ReceiveMessage(ctx, req.(*Message))
	}
	return interceptor(ctx, in, info, handler)
}

// RollerService_ServiceDesc is the grpc.ServiceDesc for RollerService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RollerService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "dice.RollerService",
	HandlerType: (*RollerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ReceiveMessage",
			Handler:    _RollerService_ReceiveMessage_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "dice.proto",
}
